// @ts-check
import { defineConfig, globalIgnores } from 'eslint/config';
import angular from 'angular-eslint';
import nx from '@nx/eslint-plugin';

export default defineConfig([
  globalIgnores([
    '**/dist',
    '**/www',
    '**/coverage',
    '**/node_modules',
    '**/.angular',
    'android',
    'ios',
    'e2e',
  ]),
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    plugins: { '@nx': nx },
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [],
          depConstraints: [
            {
              sourceTag: 'scope:trinity',
              onlyDependOnLibsWithTags: ['scope:trinity'],
            },
            {
              sourceTag: 'type:app',
              onlyDependOnLibsWithTags: [
                'type:feature',
                'type:core',
                'type:ui',
              ],
            },
            {
              sourceTag: 'type:feature',
              onlyDependOnLibsWithTags: ['type:core', 'type:ui'],
            },
            {
              sourceTag: 'type:core',
              onlyDependOnLibsWithTags: ['type:core'],
            },
            {
              // Presentational-only: no state/services, so no core dependency.
              sourceTag: 'type:ui',
              onlyDependOnLibsWithTags: ['type:ui'],
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.ts'],
    extends: [...angular.configs.tsRecommended],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/component-class-suffix': [
        'error',
        { suffixes: ['Page', 'Component'] },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'trn', style: 'kebab-case' },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'trn', style: 'camelCase' },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [...angular.configs.templateRecommended],
    rules: {},
  },
  {
    // The hand-rolled Electron package is a standalone Node/Electron app (its own
    // tsc + vitest, run via `pnpm -C electron`), not part of the libs/apps Nx graph.
    // It legitimately imports the `electron` runtime, so the lib/app module-boundary
    // rule (which misreads that as a same-project import) doesn't apply.
    files: ['electron/**/*.ts', 'electron/**/*.mts'],
    rules: {
      '@nx/enforce-module-boundaries': 'off',
    },
  },
  {
    // libs/spartan/* is canonical spartan-ng "helm" code generated by
    // @spartan-ng/cli (we own it, but don't author it). It intentionally breaks
    // our app conventions: `hlm`/`brn` selector prefixes, un-suffixed class names
    // (HlmButton), and aliased inputs (incl. `class`). Exempt it from those rules
    // rather than fighting the generator on every re-sync.
    files: ['libs/spartan/**/*.ts'],
    rules: {
      '@angular-eslint/component-class-suffix': 'off',
      '@angular-eslint/component-selector': 'off',
      '@angular-eslint/directive-selector': 'off',
      '@angular-eslint/no-input-rename': 'off',
    },
  },
]);
