import { defineSuites } from './e2e-registry.types.mts';

/** Host lifecycle definitions shared by the registry and descriptor-only configs. */
export const HOST_E2E_SUITES = defineSuites([
  {
    id: 'web.production-pwa',
    environment: 'web',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    currentTarget: 'trinity-e2e-web:production-pwa',
    delegatingTargets: ['trinity-e2e:web-e2e'],
    targetProject: 'trinity-e2e-web',
    prerequisites: ['playwright-chromium'],
    availabilityPolicy: 'required',
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:web',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    sourceEntrypoints: ['e2e/web/playwright.production-pwa.config.mts'],
  },
  {
    id: 'web.production-renderer',
    environment: 'web',
    capabilities: ['cross-capability', 'design-system'],
    contractTypes: ['accessibility', 'visual'],
    currentTarget: 'trinity-e2e-web:production-renderer',
    targetProject: 'trinity-e2e-web',
    prerequisites: ['docker', 'playwright-chromium', 'playwright-webkit'],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:web',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    sourceEntrypoints: ['e2e/web/playwright.production-renderer.config.mts'],
  },
  {
    id: 'web.container',
    environment: 'web',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    currentTarget: 'trinity-e2e-web:container',
    delegatingTargets: ['trinity-web-container:smoke'],
    targetProject: 'trinity-e2e-web',
    prerequisites: ['docker', 'playwright-chromium'],
    availabilityPolicy: 'required',
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'host',
    canonicalScript: 'e2e:web',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-web/<run-id>',
    sourceEntrypoints: ['e2e/web/playwright.container.config.mts'],
  },
  {
    id: 'electron.full',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    currentTarget: 'trinity-e2e-electron:full',
    delegatingTargets: [
      'trinity-desktop:e2e',
      'trinity-e2e-electron:full-prebuilt',
    ],
    targetProject: 'trinity-e2e-electron',
    prerequisites: ['docker', 'electron', 'xvfb'],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['electron', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:electron',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-electron/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-electron/<run-id>',
    sourceEntrypoints: ['e2e/electron/playwright.full.config.mts'],
  },
  {
    id: 'electron.smoke',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'security'],
    currentTarget: 'trinity-e2e-electron:smoke',
    delegatingTargets: [
      'trinity-desktop:e2e-smoke',
      'trinity-e2e-electron:smoke-prebuilt',
    ],
    targetProject: 'trinity-e2e-electron',
    prerequisites: ['electron', 'xvfb'],
    availabilityPolicy: 'required',
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: ['electron'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:electron',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-electron/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-electron/<run-id>',
    sourceEntrypoints: ['e2e/electron/playwright.smoke.config.mts'],
  },
  {
    id: 'android.installed-webview',
    environment: 'android',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    currentTarget: 'trinity-e2e-android:e2e',
    delegatingTargets: ['trinity-android:e2e', 'trinity-e2e:android-e2e'],
    targetProject: 'trinity-e2e-android',
    prerequisites: ['android-avd', 'android-sdk', 'docker', 'java-21', 'kvm'],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    ciRetries: 1,
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-android/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-android/<run-id>',
    sourceEntrypoints: [
      'e2e/android/run.mts',
      'e2e/android/playwright.config.mts',
    ],
  },
]);

export const ELECTRON_FULL_SUITE = HOST_E2E_SUITES[3];
export const ELECTRON_SMOKE_SUITE = HOST_E2E_SUITES[4];
export const ANDROID_INSTALLED_WEBVIEW_SUITE = HOST_E2E_SUITES[5];
