import { Injectable, inject, signal } from '@angular/core';
import {
  CryptoEvent,
  VerificationPhase,
  VerificationRequestEvent,
  VerifierEvent,
  type ShowQrCodeCallbacks,
  type ShowSasCallbacks,
  type VerificationRequest,
  type Verifier,
} from 'matrix-js-sdk/lib/crypto-api';
import { Observable, defer, from, of } from 'rxjs';
import {
  TrustCryptoPort,
  type TrustCryptoApi,
  type TrustMatrixClient,
} from '@trinity/data-access/matrix-client';
import {
  TrustOperationError,
  recoverTrustOperation,
} from './trust-operation-error';

/** UI-facing stage of the active verification (maps the SDK's numeric phase). */
export type VerificationStage =
  | 'requested'
  | 'ready'
  | 'qr-shown'
  | 'qr-confirm'
  | 'sas-shown'
  | 'waiting'
  | 'done'
  | 'cancelled';

/** One Short-Authentication-String emoji: the glyph plus its English name. */
export interface SasEmoji {
  glyph: string;
  name: string;
}

/** Plain view model of the active verification — no SDK types leak to the UI. */
export interface VerificationView {
  /** Monotonic identity for this request, used to scope transient UI intent. */
  requestId: number;
  stage: VerificationStage;
  otherUserId: string | null;
  otherDeviceId: string | null;
  /** Verifying our own other device (vs another user). MVP only does self. */
  isSelfVerification: boolean;
  /** The other side initiated the request (we should offer accept/decline). */
  incoming: boolean;
  /** The seven SAS emoji to compare — populated only in the `sas-shown` stage. */
  emoji: SasEmoji[] | null;
  /**
   * We confirmed the emoji match and are waiting for the other side to confirm too.
   * The SDK phase stays `Started` throughout, so this local flag is what tells the UI
   * to stop asking and start waiting.
   */
  sasConfirmed: boolean;
  /** The other device can scan a code generated by this one. */
  qrShowAvailable: boolean;
  /** The other device can show a code for this one to scan. */
  qrScanAvailable: boolean;
  cancelReason: string | null;
}

const SAS_METHOD = 'm.sas.v1';
const QR_SCAN_METHOD = 'm.qr_code.scan.v1';
const QR_SHOW_METHOD = 'm.qr_code.show.v1';

/**
 * Drives interactive device verification (QR or emoji SAS). Wraps the SDK's
 * `VerificationRequest`/`Verifier` so the UI never touches matrix-js-sdk: a single
 * `active` signal exposes the current verification as a {@link VerificationView},
 * and cold Observables perform the actions. Mirrors {@link TrustService}'s shape
 * (instance-keyed idempotent `connect()`/`disconnect()`).
 *
 * QR is self-device-only. SAS verification also supports another user over a DM via
 * {@link startUserVerification}.
 */
@Injectable({ providedIn: 'root' })
export class TrustVerificationService {
  private readonly cryptoPort = inject(TrustCryptoPort);
  private request: VerificationRequest | null = null;
  private verifier: Verifier | null = null;
  private sas: ShowSasCallbacks | null = null;
  private qrReciprocate: ShowQrCodeCallbacks | null = null;
  /** Presentation state only; sensitive QR bytes are emitted once and never retained. */
  private qrShown = false;
  private qrScanStarted = false;
  private sasConfirmed = false;
  private requestSequence = 0;
  private requestId = 0;

  private readonly _active = signal<VerificationView | null>(null);
  /** The active verification, or `null` when none is in flight. */
  readonly active = this._active.asReadonly();

  private readonly onIncoming = (request: VerificationRequest): void => {
    // One verification at a time (MVP): ignore new requests while one is live.
    if (this.request && !this.isTerminal(this.request)) {
      return;
    }
    this.adopt(request);
  };

  private readonly onRequestChange = (): void => {
    const req = this.request;
    if (!req) {
      return;
    }
    if (req.phase !== VerificationPhase.Ready) {
      this.qrShown = false;
    }
    // Once in flight, attach to the verifier (created by us or the other device)
    // and drive the SAS exchange.
    if (
      req.phase === VerificationPhase.Started &&
      !this.verifier &&
      req.verifier
    ) {
      this.attachVerifier(req.verifier);
    }
    this.recompute();
  };

  private readonly onShowSas = (sas: ShowSasCallbacks): void => {
    this.sas = sas;
    this.sasConfirmed = false;
    this.recompute();
  };

  private readonly onShowReciprocateQr = (qr: ShowQrCodeCallbacks): void => {
    this.qrReciprocate = qr;
    this.recompute();
  };

  private readonly onVerifierCancel = (): void => this.recompute();

  /**
   * The projection. There is no coalescing to configure because the one event is bound by
   * hand below — it carries the incoming request, which a no-arg listener could not read —
   * and an incoming verification is human-initiated, so bursts are not a thing.
   */
  private readonly projection = this.cryptoPort.project({
    id: 'crypto.verification-requests',
    bind: (client) =>
      client.on(CryptoEvent.VerificationRequestReceived, this.onIncoming),
    unbind: (client) =>
      client.off(CryptoEvent.VerificationRequestReceived, this.onIncoming),
    // Adopt a request that predates the listener (e.g. started on another device during
    // a reload). Runs on connect only, since nothing above schedules a rebuild.
    rebuild: (client) => {
      const inProgress = this.inProgressRequest(client);
      if (inProgress) {
        this.adopt(inProgress);
      }
    },
    reset: () => {
      this.clearRequest();
      this._active.set(null);
    },
  });

  /** Subscribe to incoming verification requests; pair with {@link disconnect}. */
  connect(): void {
    this.projection.connect();
  }

  /** Detach listeners and clear any active verification. */
  disconnect(): void {
    this.projection.disconnect();
    // Cleared again, unconditionally, and NOT only via the projection's `reset`. That
    // reset runs only when listeners were actually attached, but a verification can be
    // active without this service ever having connected: startSelfVerification and
    // startUserVerification call adopt() directly. Without this, disconnecting after one
    // of those leaves `active` populated and the host keeps presenting a dead request.
    // Idempotent, so the connected path clearing twice is harmless.
    this.clearRequest();
    this._active.set(null);
  }

  /** Send a verification request to our other devices (emoji SAS). */
  startSelfVerification(): Observable<void> {
    return defer(() =>
      from(
        (async (): Promise<void> => {
          const request =
            await this.requireCrypto().requestOwnUserVerification();
          this.adopt(request);
        })(),
      ),
    ).pipe(recoverTrustOperation('start-verification'));
  }

  /**
   * Request cross-user verification of `userId` over a direct-message room (emoji SAS).
   * The request is sent as an event in `roomId` (a DM with that user), and the active
   * verification is adopted so the app's host presents the SAS UI. Cold — runs on subscribe.
   */
  startUserVerification(userId: string, roomId: string): Observable<void> {
    return defer(() =>
      from(
        (async (): Promise<void> => {
          const request = await this.requireCrypto().requestVerificationDM(
            userId,
            roomId,
          );
          this.adopt(request);
        })(),
      ),
    ).pipe(recoverTrustOperation('start-verification'));
  }

  /** Accept an incoming verification request. */
  accept(): Observable<void> {
    return defer(() => from(this.requireRequest().accept())).pipe(
      recoverTrustOperation('accept-verification'),
    );
  }

  /** Begin the emoji-SAS method once the request is `ready`. */
  startSas(): Observable<void> {
    return defer(() =>
      from(
        (async (): Promise<void> => {
          this.qrShown = false;
          this.recompute();
          const verifier =
            await this.requireRequest().startVerification(SAS_METHOD);
          this.attachVerifier(verifier);
        })(),
      ),
    ).pipe(recoverTrustOperation('start-verification'));
  }

  /** Generate and reveal a QR payload only after this explicit user action. */
  showQr(): Observable<Uint8ClampedArray> {
    return defer(() =>
      from(
        (async (): Promise<Uint8ClampedArray> => {
          const request = this.requireSelfRequest();
          const data = await request.generateQRCode();
          if (!data?.length) {
            throw new TrustOperationError(
              'show-qr',
              'unsupported',
              'retry',
              'QR verification isn’t available for these sessions. Use emoji verification instead.',
            );
          }
          if (
            request !== this.request ||
            request.phase !== VerificationPhase.Ready
          ) {
            throw new TrustOperationError(
              'show-qr',
              'stale-state',
              'retry',
              'The verification request changed. Try again.',
            );
          }
          this.qrShown = true;
          this.recompute();
          return data.slice();
        })(),
      ),
    ).pipe(recoverTrustOperation('show-qr'));
  }

  /** Return from the sensitive QR display to the method chooser. */
  hideQr(): void {
    this.qrShown = false;
    this.recompute();
  }

  /** Start QR reciprocation with the raw bytes decoded from the other device. */
  scanQr(data: Uint8ClampedArray): Observable<void> {
    return defer(() =>
      from(
        (async (): Promise<void> => {
          if (!data.length) {
            throw new TrustOperationError(
              'scan-qr',
              'invalid-secret',
              'retry',
              'The scanned QR code was empty.',
            );
          }
          this.qrShown = false;
          const request = this.requireSelfRequest();
          const verifier = await request.scanQRCode(data);
          if (request !== this.request || this.isTerminal(request)) {
            verifier.cancel(
              new Error('The verification request changed while scanning.'),
            );
            return;
          }
          this.qrScanStarted = true;
          this.attachVerifier(verifier);
          this.recompute();
        })(),
      ),
    ).pipe(recoverTrustOperation('scan-qr'));
  }

  /** Confirm that the device which scanned our displayed code is in front of us. */
  confirmQr(): Observable<void> {
    return defer(() => {
      const qr = this.qrReciprocate;
      if (!qr) {
        throw new Error('There is no QR scan to confirm yet.');
      }
      qr.confirm();
      this.qrReciprocate = null;
      this.recompute();
      return of(void 0);
    }).pipe(recoverTrustOperation('confirm-verification'));
  }

  /**
   * Confirm the SAS emoji match. Our MAC is sent immediately, but the verification only
   * completes once the other side confirms too — so `sasConfirmed` flips right away and
   * the view stays in `sas-shown` until the phase moves on.
   */
  confirmSas(): Observable<void> {
    return defer(() => {
      const sas = this.sas;
      if (!sas) {
        throw new Error('There is nothing to confirm yet.');
      }
      return from(
        (async (): Promise<void> => {
          this.setSasConfirmed(true);
          try {
            await sas.confirm();
          } catch (error) {
            // Our MAC never went out, so drop back to asking rather than waiting forever.
            this.setSasConfirmed(false);
            throw error;
          }
        })(),
      );
    }).pipe(recoverTrustOperation('confirm-verification'));
  }

  /** Report that the SAS emoji do NOT match (aborts as a security failure). */
  mismatchSas(): Observable<void> {
    return defer(() => {
      this.sas?.mismatch();
      return of(void 0);
    }).pipe(recoverTrustOperation('confirm-verification'));
  }

  /** Cancel or decline the active verification. */
  cancel(): Observable<void> {
    return defer(() =>
      from(
        (async (): Promise<void> => {
          this.verifier?.cancel(new Error('Verification cancelled.'));
          const req = this.request;
          if (req && !this.isTerminal(req)) {
            await req.cancel();
          }
        })(),
      ),
    ).pipe(recoverTrustOperation('cancel-verification'));
  }

  /** Clear a finished/cancelled verification so its UI can close. */
  dismiss(): void {
    this.clearRequest();
    this._active.set(null);
  }

  // ── internals ──────────────────────────────────────────────────────────────

  private adopt(request: VerificationRequest): void {
    this.clearRequest();
    this.request = request;
    this.requestId = ++this.requestSequence;
    request.on(VerificationRequestEvent.Change, this.onRequestChange);
    if (request.phase === VerificationPhase.Started && request.verifier) {
      this.attachVerifier(request.verifier);
    }
    this.recompute();
  }

  private attachVerifier(verifier: Verifier): void {
    if (this.verifier) {
      return;
    }
    this.verifier = verifier;
    verifier.on(VerifierEvent.ShowSas, this.onShowSas);
    verifier.on(VerifierEvent.ShowReciprocateQr, this.onShowReciprocateQr);
    verifier.on(VerifierEvent.Cancel, this.onVerifierCancel);
    const sas = verifier.getShowSasCallbacks();
    if (sas) {
      this.onShowSas(sas);
    }
    const qr = verifier.getReciprocateQrCodeCallbacks();
    if (qr) {
      this.onShowReciprocateQr(qr);
    }
    // Drives the exchange and emits the method-specific prompt; the result surfaces via
    // the phase/cancel events, so the rejection here is intentionally swallowed.
    verifier.verify().catch(() => undefined);
  }

  private clearRequest(): void {
    this.request?.off(VerificationRequestEvent.Change, this.onRequestChange);
    this.verifier?.off(VerifierEvent.ShowSas, this.onShowSas);
    this.verifier?.off(
      VerifierEvent.ShowReciprocateQr,
      this.onShowReciprocateQr,
    );
    this.verifier?.off(VerifierEvent.Cancel, this.onVerifierCancel);
    this.request = null;
    this.verifier = null;
    this.sas = null;
    this.qrReciprocate = null;
    this.qrShown = false;
    this.qrScanStarted = false;
    this.sasConfirmed = false;
  }

  private setSasConfirmed(confirmed: boolean): void {
    this.sasConfirmed = confirmed;
    this.recompute();
  }

  private recompute(): void {
    const req = this.request;
    if (!req) {
      this._active.set(null);
      return;
    }
    this._active.set({
      requestId: this.requestId,
      stage: this.stageOf(req),
      otherUserId: req.otherUserId ?? null,
      otherDeviceId: req.otherDeviceId ?? null,
      isSelfVerification: req.isSelfVerification,
      incoming: !req.initiatedByMe,
      emoji:
        this.sas?.sas.emoji?.map(([glyph, name]) => ({ glyph, name })) ?? null,
      sasConfirmed: this.sasConfirmed,
      qrShowAvailable: this.qrMethodAvailable(req, QR_SCAN_METHOD),
      qrScanAvailable: this.qrMethodAvailable(req, QR_SHOW_METHOD),
      cancelReason:
        req.phase === VerificationPhase.Cancelled
          ? this.cancelReason(req)
          : null,
    });
  }

  private stageOf(req: VerificationRequest): VerificationStage {
    switch (req.phase) {
      case VerificationPhase.Unsent:
      case VerificationPhase.Requested:
        return 'requested';
      case VerificationPhase.Ready:
        if (this.qrScanStarted) {
          return 'waiting';
        }
        return this.qrShown ? 'qr-shown' : 'ready';
      case VerificationPhase.Started:
        if (this.qrReciprocate) {
          return 'qr-confirm';
        }
        return this.sas ? 'sas-shown' : 'waiting';
      case VerificationPhase.Done:
        return 'done';
      case VerificationPhase.Cancelled:
        return 'cancelled';
      default:
        return 'requested';
    }
  }

  private cancelReason(req: VerificationRequest): string {
    switch (req.cancellationCode) {
      case 'm.mismatched_sas':
        return 'The emoji did not match — verification was stopped.';
      case 'm.timeout':
        return 'The verification timed out.';
      default:
        return 'The verification was cancelled.';
    }
  }

  private isTerminal(req: VerificationRequest): boolean {
    return (
      req.phase === VerificationPhase.Done ||
      req.phase === VerificationPhase.Cancelled
    );
  }

  private inProgressRequest(
    client: TrustMatrixClient,
  ): VerificationRequest | null {
    const crypto = client.getCrypto();
    const userId = client.getUserId();
    if (!crypto || !userId) {
      return null;
    }
    return crypto.getVerificationRequestsToDeviceInProgress(userId)[0] ?? null;
  }

  private requireCrypto(): TrustCryptoApi {
    const crypto = this.cryptoPort.active().crypto;
    if (!crypto) {
      throw new TrustOperationError(
        'start-verification',
        'not-ready',
        'retry',
        'Trust is not ready for this account yet.',
      );
    }
    return crypto;
  }

  private requireRequest(): VerificationRequest {
    if (!this.request) {
      throw new TrustOperationError(
        'start-verification',
        'stale-state',
        'retry',
        'No verification is in progress.',
      );
    }
    return this.request;
  }

  private requireSelfRequest(): VerificationRequest {
    const request = this.requireRequest();
    if (!request.isSelfVerification) {
      throw new TrustOperationError(
        'show-qr',
        'unsupported',
        'none',
        'QR verification is only available between your devices.',
      );
    }
    return request;
  }

  private qrMethodAvailable(
    request: VerificationRequest,
    method: string,
  ): boolean {
    return (
      request.phase === VerificationPhase.Ready &&
      request.isSelfVerification &&
      request.otherPartySupportsMethod(method)
    );
  }
}
