/**
 * Generated by `@spartan-ng/cli:ui`, with one divergence.
 *
 * `hlm-tabs-paginated-list.ts` — the scrolling trigger row for a tab set too wide to fit —
 * was generated and then DELETED. Nothing wraps it: `@trinity/components/tabs` publishes the
 * plain list only, and the surfaces that use tabs here have three or four of them. Keeping it
 * cost real dependencies (`@angular/cdk/observers`, `@ng-icons/*`, `@trinity/helm/button`)
 * and was the only file in the kit to trip a lint rule, over `z-[1]` / `z-[2]` class strings
 * that are upstream's to write and would be clobbered on the next re-sync anyway. Re-generate
 * `tabs` if a paginated row is ever wanted; nothing here has to change for it to come back.
 */
import { HlmTabs } from './lib/hlm-tabs';
import { HlmTabsContent } from './lib/hlm-tabs-content';
import { HlmTabsContentLazy } from './lib/hlm-tabs-content-lazy';
import { HlmTabsList } from './lib/hlm-tabs-list';
import { HlmTabsTrigger } from './lib/hlm-tabs-trigger';

export * from './lib/hlm-tabs';
export * from './lib/hlm-tabs-content';
export * from './lib/hlm-tabs-content-lazy';
export * from './lib/hlm-tabs-list';
export * from './lib/hlm-tabs-trigger';

export const HlmTabsImports = [
  HlmTabs,
  HlmTabsList,
  HlmTabsTrigger,
  HlmTabsContent,
  HlmTabsContentLazy,
] as const;
