import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ESLint } from 'eslint';

/**
 * Guards the two lint invariants that a green `pnpm lint` cannot see.
 *
 * A linter upgrade that fails loudly is cheap. One that silently stops APPLYING a rule is
 * not: the run stays green, fewer things are enforced, and nothing says so. That is not
 * hypothetical here — ESLint 10 pulled `@eslint/config-array` 0.21 -> 0.23, which carries
 * an upstream breaking `minimatch` 3 -> 10 swap, i.e. a change to the very glob engine that
 * decides which config block a file gets. It happened to be inert; the point is that a
 * green lint was not evidence of that, and the check was done by hand and then thrown away.
 *
 * These assertions are deliberately about the SHAPE of the resolved config rather than its
 * size. Counting rules would fail on every legitimate rule addition and get deleted the
 * first time it cried wolf.
 */

const workspaceRoot = join(import.meta.dirname, '..');

/** One ESLint instance for the whole file — construction dominates the runtime. */
const eslint = new ESLint({ cwd: workspaceRoot });

const resolve = (relativePath) =>
  eslint.calculateConfigForFile(join(workspaceRoot, relativePath));

/** Severity as ESLint reports it in a resolved config: [severity, ...options]. */
const severityOf = (config, ruleId) => {
  const entry = config.rules?.[ruleId];
  return Array.isArray(entry) ? entry[0] : entry;
};

/**
 * The four rules `libs/spartan/*` is exempt from, because that code is generated by
 * `@spartan-ng/cli` and owned upstream — see the `trn` prefix rule in CLAUDE.md.
 */
const SPARTAN_EXEMPT_RULES = [
  '@angular-eslint/no-input-rename',
  '@angular-eslint/component-class-suffix',
  '@angular-eslint/component-selector',
  '@angular-eslint/directive-selector',
];

describe('lint invariants', () => {
  it('exempts libs/spartan from exactly the four generated-code rules, and nothing else', async () => {
    const app = await resolve('libs/ui/src/index.ts');
    const spartan = await resolve(
      'libs/spartan/tooltip/src/lib/hlm-tooltip.ts',
    );

    for (const ruleId of SPARTAN_EXEMPT_RULES) {
      expect(
        severityOf(app, ruleId),
        `${ruleId} must be an error outside spartan`,
      ).toBe(2);
      expect(
        severityOf(spartan, ruleId),
        `${ruleId} must be off inside spartan`,
      ).toBe(0);
    }

    // The other half of the invariant, and the half a per-rule check would miss: the
    // exemption must not have WIDENED. Anything else the two configs disagree on means a
    // glob started matching more than it was written to.
    const ruleIds = new Set([
      ...Object.keys(app.rules ?? {}),
      ...Object.keys(spartan.rules ?? {}),
    ]);
    const differing = [...ruleIds].filter(
      (ruleId) =>
        JSON.stringify(app.rules?.[ruleId]) !==
        JSON.stringify(spartan.rules?.[ruleId]),
    );

    expect(differing.sort()).toEqual([...SPARTAN_EXEMPT_RULES].sort());
  });

  it('keeps the type-aware and boundary guards enabled on first-party TypeScript', async () => {
    const config = await resolve('libs/ui/src/index.ts');

    // Type-aware, and the rule most likely to lose its files silently: it needs
    // parserOptions.projectService, and a file the service does not own is skipped
    // rather than reported.
    expect(severityOf(config, '@typescript-eslint/no-deprecated')).toBe(2);
    expect(config.languageOptions?.parserOptions?.projectService).toBe(true);

    // The architectural guard behind every @trinity/* boundary.
    expect(severityOf(config, '@nx/enforce-module-boundaries')).toBe(2);
  });

  it('lints Angular templates through the template parser, not the TypeScript one', async () => {
    const template = await resolve(
      'libs/feature/rooms/src/lib/message-row/message-row.component.html',
    );

    // Templates resolve a genuinely different chain — a different parser and a much
    // smaller rule set. A config change that collapsed the two would leave templates
    // linted by the wrong parser and reporting nothing, while `pnpm lint` stayed green.
    expect(template.languageOptions?.parser?.meta?.name ?? '').toContain(
      'template-parser',
    );
    expect(Object.keys(template.rules ?? {}).length).toBeGreaterThan(0);
  });
});
