import { globSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ESLint } from 'eslint';

/**
 * Guards the two lint invariants that a green `pnpm lint` cannot see.
 *
 * A linter upgrade that fails loudly is cheap. One that silently stops APPLYING a rule is
 * not: the run stays green, fewer things are enforced, and nothing says so. That is not
 * hypothetical here — ESLint 10 pulled `@eslint/config-array` 0.21 -> 0.23, which carries
 * an upstream breaking `minimatch` 3 -> 10 swap, i.e. a change to the very glob engine that
 * decides which config block a file gets. It happened to be inert; the point is that a
 * green lint was not evidence of that, and the check was done by hand and then thrown away.
 *
 * These assertions are deliberately about the SHAPE of the resolved config rather than its
 * size. Counting rules would fail on every legitimate rule addition and get deleted the
 * first time it cried wolf.
 */

const workspaceRoot = join(import.meta.dirname, '..');

/** One ESLint instance for the whole file — construction dominates the runtime. */
const eslint = new ESLint({ cwd: workspaceRoot });

const resolve = (relativePath) =>
  eslint.calculateConfigForFile(join(workspaceRoot, relativePath));

/** Severity as ESLint reports it in a resolved config: [severity, ...options]. */
const severityOf = (config, ruleId) => {
  const entry = config.rules?.[ruleId];
  return Array.isArray(entry) ? entry[0] : entry;
};

/**
 * The four rules `libs/spartan/*` is exempt from, because that code is generated by
 * `@spartan-ng/cli` and owned upstream — see the `trn` prefix rule in CLAUDE.md.
 */
const SPARTAN_EXEMPT_RULES = [
  '@angular-eslint/no-input-rename',
  '@angular-eslint/component-class-suffix',
  '@angular-eslint/component-selector',
  '@angular-eslint/directive-selector',
];

describe('lint invariants', () => {
  it('exempts libs/spartan from exactly the four generated-code rules, and nothing else', async () => {
    const app = await resolve('libs/ui/src/index.ts');
    const spartan = await resolve(
      'libs/spartan/tooltip/src/lib/hlm-tooltip.ts',
    );

    for (const ruleId of SPARTAN_EXEMPT_RULES) {
      expect(
        severityOf(app, ruleId),
        `${ruleId} must be an error outside spartan`,
      ).toBe(2);
      expect(
        severityOf(spartan, ruleId),
        `${ruleId} must be off inside spartan`,
      ).toBe(0);
    }

    // The other half of the invariant, and the half a per-rule check would miss: the
    // exemption must not have WIDENED. Anything else the two configs disagree on means a
    // glob started matching more than it was written to.
    const ruleIds = new Set([
      ...Object.keys(app.rules ?? {}),
      ...Object.keys(spartan.rules ?? {}),
    ]);
    const differing = [...ruleIds].filter(
      (ruleId) =>
        JSON.stringify(app.rules?.[ruleId]) !==
        JSON.stringify(spartan.rules?.[ruleId]),
    );

    expect(differing.sort()).toEqual([...SPARTAN_EXEMPT_RULES].sort());
  });

  it('keeps the type-aware and boundary guards enabled on first-party TypeScript', async () => {
    const config = await resolve('libs/ui/src/index.ts');

    // Type-aware, and the rule most likely to lose its files silently: it needs
    // parserOptions.projectService, and a file the service does not own is skipped
    // rather than reported.
    expect(severityOf(config, '@typescript-eslint/no-deprecated')).toBe(2);
    expect(config.languageOptions?.parserOptions?.projectService).toBe(true);

    // The architectural guard behind every @trinity/* boundary.
    expect(severityOf(config, '@nx/enforce-module-boundaries')).toBe(2);
  });

  it('type-aware-lints the Playwright suite, so a dropped await cannot pass vacuously', async () => {
    // The e2e tree was in `globalIgnores` for most of this repo's life, which is a state
    // a config edit can restore in one line and `pnpm lint` will report as green — there
    // is simply less to lint. These two rules are the reason the ignore was removed:
    // no-floating-promises catches `expect(locator).toBeVisible()` without its `await`
    // (the assertion never runs, the spec passes whatever the app did), and the `.only`
    // ban catches a focused test that silently reduces the suite to one spec.
    const spec = await resolve('e2e/playwright/app.spec.mts');

    expect(severityOf(spec, '@typescript-eslint/no-floating-promises')).toBe(2);
    expect(severityOf(spec, 'no-restricted-syntax')).toBe(2);
    // no-floating-promises is type-aware: without a program behind it the rule loads and
    // reports nothing at all, which looks identical to a clean suite.
    expect(spec.languageOptions?.parserOptions?.project ?? []).toContain(
      './e2e/tsconfig.json',
    );
  });

  it('lints Angular templates through the template parser, not the TypeScript one', async () => {
    const template = await resolve(
      'libs/feature/rooms/src/lib/message-row/message-row.component.html',
    );

    // Templates resolve a genuinely different chain — a different parser and a much
    // smaller rule set. A config change that collapsed the two would leave templates
    // linted by the wrong parser and reporting nothing, while `pnpm lint` stayed green.
    expect(template.languageOptions?.parser?.meta?.name ?? '').toContain(
      'template-parser',
    );
    expect(Object.keys(template.rules ?? {}).length).toBeGreaterThan(0);
  });
});

/**
 * Which tier may reach which third-party UI package, as a table rather than a rule, so the
 * asymmetries are stated instead of inferred. Every `banned` entry must be refused and
 * every `allowed` entry must stay reachable — a ban that widens onto the wrapper layer is
 * as much a regression as one that disappears.
 */
const ALL_UI_VENDORS = [
  '@spartan-ng/brain',
  '@angular/cdk',
  '@ng-icons',
  '@ctrl/ngx-emoji-mart',
];

const UI_BOUNDARY = [
  // libs/ui keeps nothing. Both wrappers it was once expected to host went to the kit
  // instead — <trn-icon> in #154, <trn-emoji-picker> in #152 — because a lib tagged
  // ui:wrapper is precisely the tier that may not name a vendor.
  //
  // @angular/cdk was the last vendor still allowed here, and this table used to assert that
  // it must STAY allowed "because it is the layer that wraps it". That was never true of
  // libs/ui: it imports no vendor at all, and the layer that wraps CDK is
  // @trinity/helm/overlay, tagged ui:vendor-wrapper. The assertion was pinning open a hole
  // rather than protecting a need — and since libs/ui is type:ui, which every feature lib
  // may depend on, unmediated CDK reaching it would have propagated straight to features.
  { tier: 'ui:wrapper', banned: ALL_UI_VENDORS, allowed: [] },
  // #151 and #154 closed the dialog, toast and icon imports; #152 closed the last one.
  // Every tier below the UI layer is now banned from every vendor, and nothing is staged —
  // the `warn` block that made the count visible while it shrank has been deleted, which
  // is what "the gate is closed" means for #148.
  { tier: 'type:feature', banned: ALL_UI_VENDORS, allowed: [] },
  { tier: 'type:data-access', banned: ALL_UI_VENDORS, allowed: [] },
  { tier: 'type:util', banned: ALL_UI_VENDORS, allowed: [] },
  { tier: 'type:platform', banned: ALL_UI_VENDORS, allowed: [] },
  { tier: 'type:app', banned: ALL_UI_VENDORS, allowed: [] },
];

/**
 * The projects deliberately outside the vendor bans, listed so the exemption is a decision
 * somebody made rather than a gap nobody noticed.
 *
 * - `e2e` (`type:e2e`) drives a real browser from node. It renders no Angular UI, and it
 *   must be free to import whatever a Playwright spec needs.
 * - `scripts` (`type:tool`) is node tooling — guards, codegen, version checks.
 *
 * The vendored kit is not listed here: it is exempted by its `ui:vendor-wrapper` tag in the
 * filter below, since it is the layer the bans exist to protect rather than an exception to
 * them.
 *
 * `trinity-desktop` (the Electron shell) is not listed either, and no longer needs to be: it
 * used to be the one Nx project with no tags AND no project.json for a glob to find, so this
 * guard could not see the single project it could not vouch for. It now carries
 * `type:app`/`scope:shared` in `electron/project.json` and is swept below like anything else.
 */
const OUTSIDE_THE_VENDOR_BANS = ['e2e/project.json', 'scripts/project.json'];

describe('UI vendor boundary', () => {
  const tagsOf = (project) =>
    JSON.parse(
      readFileSync(join(workspaceRoot, project, 'project.json'), 'utf8'),
    ).tags ?? [];

  it('gives the wrapper and the vendored kit distinct tags, which is what any rule keys on', () => {
    // Both were ['type:ui', 'scope:shared'] and nothing else, so no boundary rule could
    // express "only the kit may import brain" — the two were indistinguishable to Nx.
    // If these collapse back to being equal, every ban below silently covers both or
    // neither, and lint still passes.
    expect(tagsOf('libs/ui')).toContain('ui:wrapper');
    expect(tagsOf('libs/spartan/button')).toContain('ui:vendor-wrapper');
    expect(tagsOf('libs/ui')).not.toContain('ui:vendor-wrapper');
  });

  it('gives every project a tag the vendor bans actually key on', async () => {
    // The failure mode this exists for is silent and unbounded. `depConstraints` entries
    // are keyed on `sourceTag`, and there is deliberately no `sourceTag: '*'` catch-all —
    // so a project whose tags match NO entry gets no layering rule and, worse, none of the
    // `bannedExternalImports` below. A new lib generated without tags, or one carrying
    // `type:featrue`, may import @ctrl/ngx-emoji-mart or reach across any boundary it
    // likes, and `pnpm lint` reports success. Every ban in this file is only as complete
    // as the tagging is.
    //
    // Checked against the CONFIG's own source tags rather than against the `type:`/`scope:`
    // prefixes. The prefix form was the bug: `type:featrue` starts with `type:`, so the
    // exact typo named above sailed through the very guard written to catch it. Only a
    // comparison with the tags that key a ban can tell "tagged" from "covered".
    const config = await resolve('libs/ui/src/index.ts');
    const constraints =
      config.rules['@nx/enforce-module-boundaries'][1].depConstraints;
    const tagsCarryingBans = new Set(
      constraints
        .filter((entry) => entry.bannedExternalImports?.length)
        .map((entry) => entry.sourceTag),
    );
    expect(tagsCarryingBans.size).toBeGreaterThan(0);

    // Swept beyond {apps,libs}: `e2e` and `scripts` are Nx projects too, and the previous
    // glob simply could not see them — so "tags every project" was asserted over 41 of the
    // 43 project.json files in the tree and passed on a sweep that never looked.
    const projects = globSync(
      '{apps,libs,e2e,scripts,electron}/**/project.json',
      { cwd: workspaceRoot },
    );
    // An empty sweep must not pass as a clean one — the same trap the host-directives
    // guard was written around.
    expect(projects.length).toBeGreaterThan(30);

    const uncovered = projects
      .map((path) => ({ path, tags: tagsOf(dirname(path)) }))
      .filter(
        ({ tags }) =>
          !tags.some((tag) => tagsCarryingBans.has(tag)) &&
          // The vendored kit is uncovered on purpose — it IS the wrapper layer, and a ban
          // there would ban the layer from existing. Exempted by its TAG rather than by
          // listing 19 paths, so adding a kit library is not a test edit, while a lib that
          // is uncovered for any OTHER reason still fails below.
          !tags.includes('ui:vendor-wrapper'),
      )
      .map(({ path }) => path)
      .sort();

    expect(uncovered).toEqual(OUTSIDE_THE_VENDOR_BANS);
  });

  it('keeps the app-tier vendor stylesheets to the two the ban cannot cover', () => {
    // `bannedExternalImports` matches TS/JS import specifiers, and nothing else. The app's
    // build `styles` array is configuration, so a vendor stylesheet listed there is
    // invisible to every rule above — the boundary is enforced for code and silent here.
    // Both entries below are deliberate and both have to live at this tier: CDK's overlay
    // sheet must be global for any overlay to position at all, and while the emoji picker's
    // CAN be pulled into the lazy component chunk (`@import '@ctrl/ngx-emoji-mart/picker'`
    // resolves and inlines), doing so puts that component 517 bytes over the workspace's
    // 8 kB `anyComponentStyle` budget — and raising a budget that guards every component,
    // to relocate one vendored file, is the worse trade.
    //
    // So this is pinned rather than fixed: the list is a decision with a reason, and a third
    // entry has to be argued for here instead of appearing in a build config nobody reads as
    // part of the boundary.
    const app = JSON.parse(
      readFileSync(join(workspaceRoot, 'apps/trinity/project.json'), 'utf8'),
    );
    const vendorStyles = app.targets.build.options.styles.filter((style) =>
      style.startsWith('node_modules/'),
    );

    expect(vendorStyles).toEqual([
      'node_modules/@angular/cdk/overlay-prebuilt.css',
      'node_modules/@ctrl/ngx-emoji-mart/picker.css',
    ]);
  });

  it('bans the vendors from every tier that should not render third-party UI', async () => {
    const config = await resolve('libs/ui/src/index.ts');
    const constraints =
      config.rules['@nx/enforce-module-boundaries'][1].depConstraints;
    const bannedFor = (tier) =>
      constraints.find((entry) => entry.sourceTag === tier)
        ?.bannedExternalImports ?? [];
    // Deliberately ignores the trailing `*`: this test asks whether a ban for the vendor
    // was DECLARED, and the test below asks whether it can actually match. Keeping those
    // apart means a star-less glob fails exactly one of them, naming the real defect. Do
    // not fold them together — a combined check would report "no ban" for what is really
    // "a ban that silently matches nothing".
    const covers = (globs, vendor) =>
      globs.some((glob) => vendor.startsWith(glob.replace(/\*$/, '')));

    for (const { tier, banned, allowed } of UI_BOUNDARY) {
      const globs = bannedFor(tier);
      for (const vendor of banned) {
        expect(
          covers(globs, vendor),
          `${tier} must not be allowed to import ${vendor}`,
        ).toBe(true);
      }
      for (const vendor of allowed) {
        expect(
          covers(globs, vendor),
          `${tier} must stay able to import ${vendor} — it is the layer that wraps it`,
        ).toBe(false);
      }
    }
  });

  it('keeps a trailing * on every banned glob, without which the ban matches nothing', async () => {
    const config = await resolve('libs/ui/src/index.ts');
    const constraints =
      config.rules['@nx/enforce-module-boundaries'][1].depConstraints;

    // The failure mode this exists for: `bannedExternalImports` is matched as a glob, so
    // a bare '@angular/cdk' matches only the bare specifier — which nothing imports, since
    // every real import is a deep '@angular/cdk/dialog'. The rule then reports SUCCESS,
    // and the ban reads as enforced while enforcing nothing. Measured, not assumed.
    const globs = constraints.flatMap(
      (entry) => entry.bannedExternalImports ?? [],
    );
    expect(globs.length).toBeGreaterThan(0);
    expect(globs.filter((glob) => !glob.endsWith('*'))).toEqual([]);
  });

  it('leaves the vendored kit itself free to import its own vendor', async () => {
    const kit = await resolve('libs/spartan/tooltip/src/lib/hlm-tooltip.ts');
    const constraints =
      kit.rules['@nx/enforce-module-boundaries'][1].depConstraints;

    // The kit IS the wrapper; banning brain there would ban the layer from existing.
    //
    // Asserted against `bannedExternalImports` specifically, not against the entry: a
    // future `ui:vendor-wrapper` constraint that does something else entirely — an
    // `onlyDependOnLibsWithTags`, say — is not a violation of this invariant, and a test
    // that failed on it would be crying wolf.
    expect(
      constraints.find((entry) => entry.sourceTag === 'ui:vendor-wrapper')
        ?.bannedExternalImports,
    ).toBeUndefined();
    expect(kit.rules['no-restricted-imports']).toBeUndefined();
  });

  it('keeps the matrix-js-sdk dynamic-import ban after the staging block was deleted', async () => {
    const feature = await resolve('libs/feature/rooms/src/lib/rooms.routes.ts');

    // #148's staged `no-restricted-imports` block is gone — every vendor is enforced
    // through depConstraints now. What must NOT have gone with it is the matrix-js-sdk
    // selector: flat config replaces a rule's options wholesale, so removing a block that
    // configured `no-restricted-syntax` over the same glob is exactly how that ban would
    // disappear silently. Every route here is lazy, so this selector is the half that
    // matters.
    const syntax = feature.rules['no-restricted-syntax'];
    expect(syntax[0]).toBe(2);
    expect(
      syntax
        .slice(1)
        .some((option) => /matrix-js-sdk/.test(option?.selector ?? '')),
    ).toBe(true);

    // And nothing is staged at `warn` any more.
    expect(severityOf(feature, 'no-restricted-imports') ?? 0).toBe(0);
    expect(
      severityOf(feature, '@typescript-eslint/no-restricted-imports'),
    ).toBe(2);
  });
});
