/**
 * Every icon Trinity uses, named in Trinity's own vocabulary.
 *
 * Declared as a `const` array so the same list is both a compile-time union and a runtime
 * one — `trn-icon-name.spec.ts` walks it to prove no name has gone unused, which matters
 * because the vendor map below is provided eagerly at the app root and can therefore never
 * tree-shake an entry away.
 *
 * These are deliberately NOT the lucide identifiers. The union is ours, so swapping icon
 * packs is a change to {@link TRN_ICONS} alone rather than to 116 call sites; and unlike
 * `@ng-icons`' own `IconType = IconName | (string & {})`, which accepts any string at all,
 * a typo here is a compile error.
 */
export const TRN_ICON_NAMES = [
  'archive',
  'arrow-down-wide-narrow',
  'arrow-left',
  'bell',
  'bell-off',
  'bold',
  'braces',
  'calendar-search',
  'camera',
  'check',
  'check-check',
  'chevron-down',
  'chevron-right',
  'chevron-up',
  'circle-dot',
  'circle-minus',
  'clock',
  'cloud-off',
  'code',
  'command',
  'copy',
  'crown',
  'door-open',
  'download',
  'ellipsis',
  'ellipsis-vertical',
  'eye',
  'eye-off',
  'flag',
  'flask-conical',
  'folder-plus',
  'forward',
  'house',
  'image',
  'image-play',
  'italic',
  'key-round',
  'keyboard',
  'layers',
  'link',
  'list',
  'list-ordered',
  'list-todo',
  'loader-circle',
  'locate-fixed',
  'lock',
  'log-out',
  'mail',
  'mail-open',
  'map-pin',
  'message-square',
  'messages-square',
  'mic',
  'monitor-smartphone',
  'palette',
  'paperclip',
  'pause',
  'pencil',
  'pin',
  'pin-off',
  'play',
  'plus',
  'quote',
  'reply',
  'rotate-ccw',
  'search',
  'send',
  'server',
  'settings',
  'shield',
  'shield-alert',
  'shield-check',
  'shield-question',
  'smile',
  'square-code',
  'star',
  'strikethrough',
  'text-quote',
  'trash-2',
  'user',
  'user-plus',
  'users',
  'vote',
  'x',
] as const;

export type TrnIconName = (typeof TRN_ICON_NAMES)[number];
