import { defineSuites } from '../types.mts';

export const COMPONENT_E2E_SUITES = defineSuites([
  {
    id: 'components.storybook',
    environment: 'components',
    capabilities: ['design-system'],
    contractTypes: ['accessibility', 'visual'],
    currentTarget: 'trinity-e2e:storybook-e2e',
    targetProject: 'trinity-e2e-components',
    prerequisites: ['playwright-chromium', 'playwright-webkit'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/storybook',
    targetArtifactRoot: 'dist/.playwright/components/storybook',
    sourceEntrypoints: ['e2e/playwright.storybook.config.mts'],
  },
  {
    id: 'components.styling',
    environment: 'components',
    capabilities: ['design-system'],
    contractTypes: ['visual'],
    currentTarget: 'trinity-e2e:styling-e2e',
    targetProject: 'trinity-e2e-components',
    prerequisites: ['playwright-chromium'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/styling',
    targetArtifactRoot: 'dist/.playwright/components/styling',
    sourceEntrypoints: ['e2e/playwright.styling.config.mts'],
  },
  {
    id: 'components.scrollbars',
    environment: 'components',
    capabilities: ['design-system', 'settings'],
    contractTypes: ['visual'],
    currentTarget: 'trinity-e2e:scrollbars-e2e',
    targetProject: 'trinity-e2e-components',
    prerequisites: [
      'docker',
      'playwright-chromium',
      'playwright-firefox',
      'playwright-webkit',
    ],
    ciTier: 'scheduled',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/e2e',
    targetArtifactRoot: 'dist/.playwright/components/scrollbars',
    sourceEntrypoints: ['e2e/playwright.scrollbars.config.mts'],
  },
]);
