import { defineSuites } from '../types.mts';

export const COMPONENT_E2E_SUITES = defineSuites([
  {
    id: 'components.storybook',
    environment: 'components',
    capabilities: ['design-system'],
    contractTypes: ['accessibility', 'visual'],
    currentTarget: 'trinity-e2e-components:storybook',
    delegatingTargets: ['trinity-e2e:storybook-e2e'],
    targetProject: 'trinity-e2e-components',
    prerequisites: ['playwright-chromium', 'playwright-webkit'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    sourceEntrypoints: ['e2e/components/playwright.storybook.config.mts'],
  },
  {
    id: 'components.styling',
    environment: 'components',
    capabilities: ['design-system'],
    contractTypes: ['visual'],
    currentTarget: 'trinity-e2e-components:styling',
    delegatingTargets: ['trinity-e2e:styling-e2e'],
    targetProject: 'trinity-e2e-components',
    prerequisites: ['playwright-chromium'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    sourceEntrypoints: ['e2e/components/playwright.styling.config.mts'],
  },
  {
    id: 'components.scrollbars',
    environment: 'components',
    capabilities: ['design-system', 'settings'],
    contractTypes: ['visual'],
    currentTarget: 'trinity-e2e-components:scrollbars',
    delegatingTargets: ['trinity-e2e:scrollbars-e2e'],
    targetProject: 'trinity-e2e-components',
    prerequisites: [
      'docker',
      'playwright-chromium',
      'playwright-firefox',
      'playwright-webkit',
    ],
    ciTier: 'scheduled',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    sourceEntrypoints: ['e2e/components/playwright.scrollbars.config.mts'],
  },
  {
    id: 'components.production-renderer',
    environment: 'components',
    capabilities: ['cross-capability', 'design-system'],
    contractTypes: ['accessibility', 'visual'],
    currentTarget: 'trinity-e2e-components:production-renderer',
    targetProject: 'trinity-e2e-components',
    prerequisites: ['docker', 'playwright-chromium', 'playwright-webkit'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:components',
    currentArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-components/<run-id>',
    sourceEntrypoints: [
      'e2e/components/playwright.production-renderer.config.mts',
    ],
  },
]);
