import { defineSuites } from '../types.mts';

export const HOST_E2E_SUITES = defineSuites([
  {
    id: 'web.production-pwa',
    environment: 'web',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    currentTarget: 'trinity-e2e:web-e2e',
    targetProject: 'trinity-e2e-web',
    prerequisites: ['playwright-chromium'],
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:web',
    currentArtifactRoot: 'dist/.playwright/web',
    targetArtifactRoot: 'dist/.playwright/web/production-pwa',
    sourceEntrypoints: ['e2e/playwright.web.config.mts'],
  },
  {
    id: 'electron.full',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    currentTarget: 'trinity-desktop:e2e',
    targetProject: 'trinity-e2e-electron',
    prerequisites: ['docker', 'electron', 'playwright-chromium', 'xvfb'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['electron', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:electron',
    currentArtifactRoot: 'dist/.playwright/electron',
    targetArtifactRoot: 'dist/.playwright/electron/full',
    sourceEntrypoints: ['e2e/playwright.electron.config.mts'],
  },
  {
    id: 'electron.smoke',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'security'],
    currentTarget: 'trinity-desktop:e2e-smoke',
    targetProject: 'trinity-e2e-electron',
    prerequisites: ['electron', 'playwright-chromium', 'xvfb'],
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: ['electron'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:electron',
    currentArtifactRoot: 'dist/.playwright/electron',
    targetArtifactRoot: 'dist/.playwright/electron/smoke',
    sourceEntrypoints: ['e2e/playwright.electron.smoke.config.mts'],
  },
  {
    id: 'android.installed-webview',
    environment: 'android',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    currentTarget: 'trinity-android:e2e',
    delegatingTargets: ['trinity-e2e:android-e2e'],
    targetProject: 'trinity-e2e-android',
    prerequisites: ['android-avd', 'docker', 'playwright-chromium'],
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android',
    currentArtifactRoot: 'dist/.playwright/android',
    targetArtifactRoot: 'dist/.playwright/android/installed-webview',
    sourceEntrypoints: [
      'e2e/android/run.mts',
      'e2e/playwright.android.config.mts',
    ],
  },
]);
