import { defineSuites } from '../types.mts';

const artifactRoot = 'dist/.playwright/trinity-e2e-protocol/<run-id>';

const synapseProtocol = {
  environment: 'protocol',
  prerequisites: ['docker', 'playwright-chromium'],
  availabilityPolicy: 'required',
  cachePolicy: 'never',
  serializationKeys: ['synapse'],
  timeoutClass: 'long',
  canonicalScript: 'e2e:protocol',
  currentArtifactRoot: artifactRoot,
  targetArtifactRoot: artifactRoot,
  targetProject: 'trinity-e2e-protocol',
} as const;

const standaloneProtocol = {
  environment: 'protocol',
  availabilityPolicy: 'required',
  cachePolicy: 'never',
  timeoutClass: 'medium',
  canonicalScript: 'e2e:protocol',
  currentArtifactRoot: artifactRoot,
  targetArtifactRoot: artifactRoot,
  targetProject: 'trinity-e2e-protocol',
} as const;

export const PROTOCOL_E2E_SUITES = defineSuites([
  {
    ...synapseProtocol,
    id: 'protocol.verify-sas',
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:verify-sas',
    ciTier: 'local-only',
    sourceEntrypoints: [
      'e2e/protocol/playwright.config.mts',
      'e2e/protocol/verify-sas.spec.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.verify-qr',
    ciPreparation: { buildTarget: 'trinity:build:development' },
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:verify-qr',
    ciTier: 'pull-request',
    sourceEntrypoints: ['e2e/protocol/verify-qr.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.media',
    capabilities: ['conversations', 'media'],
    contractTypes: ['journey', 'protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:media',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/send-media.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.threads',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:threads',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/threads.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.reply',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:reply',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/reply.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.spaces',
    capabilities: ['room-library'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:spaces',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/spaces.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.rooms',
    capabilities: ['room-library'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:rooms',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/rooms.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.search',
    capabilities: ['conversations', 'search'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:search',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/search.spec.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.emoji',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:emoji',
    ciTier: 'scheduled',
    sourceEntrypoints: ['e2e/protocol/emoji.spec.mjs'],
  },
  {
    ...standaloneProtocol,
    id: 'protocol.verify-sas-selfcheck',
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:verify-sas-selfcheck',
    prerequisites: ['network', 'playwright-chromium'],
    ciTier: 'local-only',
    serializationKeys: [],
    sourceEntrypoints: ['e2e/protocol/verify-sas-selfcheck.spec.mjs'],
  },
  {
    ...standaloneProtocol,
    id: 'protocol.crypto-spike-chromium',
    capabilities: ['matrix-runtime', 'trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:crypto-spike-chromium',
    prerequisites: ['playwright-chromium'],
    ciTier: 'scheduled',
    serializationKeys: ['crypto-spike'],
    sourceEntrypoints: ['e2e/protocol/crypto-spike.spec.mjs'],
  },
  {
    ...standaloneProtocol,
    id: 'protocol.crypto-spike-webkit',
    capabilities: ['matrix-runtime', 'trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e-protocol:crypto-spike-webkit',
    prerequisites: ['playwright-webkit'],
    ciTier: 'scheduled',
    serializationKeys: ['crypto-spike'],
    sourceEntrypoints: ['e2e/protocol/crypto-spike.spec.mjs'],
  },
  {
    ...standaloneProtocol,
    id: 'protocol.login-smoke',
    capabilities: ['accounts', 'discovery'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e-protocol:login-smoke',
    prerequisites: ['network', 'playwright-chromium'],
    ciTier: 'local-only',
    serializationKeys: [],
    sourceEntrypoints: ['e2e/protocol/smoke-login.spec.mjs'],
  },
]);
