import { defineSuites } from '../types.mts';

const synapseProtocol = {
  environment: 'protocol',
  prerequisites: ['docker', 'playwright-chromium'],
  cachePolicy: 'never',
  serializationKeys: ['synapse'],
  timeoutClass: 'long',
  canonicalScript: 'e2e:protocol',
  currentArtifactRoot: 'e2e/.artifacts',
  targetProject: 'trinity-e2e-protocol',
} as const;

export const PROTOCOL_E2E_SUITES = defineSuites([
  {
    ...synapseProtocol,
    id: 'protocol.verify-sas',
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-verify-sas',
    ciTier: 'local-only',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/verify-sas.mjs',
      'e2e/runners/verify-sas-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.verify-qr',
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-verify-qr',
    ciTier: 'pull-request',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/verify-qr.mjs',
      'e2e/runners/verify-qr-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.media',
    capabilities: ['conversations', 'media'],
    contractTypes: ['journey', 'protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-media',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/send-media.mjs',
      'e2e/runners/send-media-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.threads',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-threads',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/threads.mjs',
      'e2e/runners/threads-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.reply',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-reply',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/reply.mjs', 'e2e/runners/reply-run.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.spaces',
    capabilities: ['room-library'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-spaces',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/spaces.mjs',
      'e2e/runners/spaces-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.rooms',
    capabilities: ['room-library'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-rooms',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/rooms.mjs', 'e2e/runners/rooms-run.mjs'],
  },
  {
    ...synapseProtocol,
    id: 'protocol.search',
    capabilities: ['conversations', 'search'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-search',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: [
      'e2e/features/search.mjs',
      'e2e/runners/search-run.mjs',
    ],
  },
  {
    ...synapseProtocol,
    id: 'protocol.emoji',
    capabilities: ['conversations'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-emoji',
    ciTier: 'scheduled',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/emoji.mjs', 'e2e/runners/emoji-run.mjs'],
  },
  {
    id: 'protocol.verify-sas-selfcheck',
    environment: 'protocol',
    capabilities: ['trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-verify-sas-selfcheck',
    targetProject: 'trinity-e2e-protocol',
    prerequisites: ['network', 'playwright-chromium'],
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:protocol',
    currentArtifactRoot: 'e2e/.artifacts',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/verify-sas-selfcheck.mjs'],
  },
  {
    id: 'protocol.crypto-spike-chromium',
    environment: 'protocol',
    capabilities: ['matrix-runtime', 'trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-crypto-spike-chromium',
    targetProject: 'trinity-e2e-protocol',
    prerequisites: ['playwright-chromium'],
    ciTier: 'scheduled',
    cachePolicy: 'never',
    serializationKeys: ['crypto-spike'],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:protocol',
    currentArtifactRoot: 'e2e/.artifacts',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/crypto-spike.mjs'],
  },
  {
    id: 'protocol.crypto-spike-webkit',
    environment: 'protocol',
    capabilities: ['matrix-runtime', 'trust'],
    contractTypes: ['protocol', 'security'],
    currentTarget: 'trinity-e2e:protocol-crypto-spike-webkit',
    targetProject: 'trinity-e2e-protocol',
    prerequisites: ['playwright-webkit'],
    ciTier: 'scheduled',
    cachePolicy: 'never',
    serializationKeys: ['crypto-spike'],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:protocol',
    currentArtifactRoot: 'e2e/.artifacts',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/crypto-spike.mjs'],
  },
  {
    id: 'protocol.login-smoke',
    environment: 'protocol',
    capabilities: ['accounts', 'discovery'],
    contractTypes: ['journey', 'protocol'],
    currentTarget: 'trinity-e2e:protocol-login-smoke',
    targetProject: 'trinity-e2e-protocol',
    prerequisites: ['network', 'playwright-chromium'],
    ciTier: 'local-only',
    cachePolicy: 'never',
    serializationKeys: [],
    timeoutClass: 'medium',
    canonicalScript: 'e2e:protocol',
    currentArtifactRoot: 'e2e/.artifacts',
    targetArtifactRoot: 'dist/.playwright/trinity-e2e-protocol/<run-id>',
    sourceEntrypoints: ['e2e/features/smoke-login.mjs'],
  },
]);
