import { defineSuites } from '../types.mts';

const artifactRoot = (targetProject: string): string =>
  `dist/.playwright/${targetProject}/<run-id>`;

/** Node test runner coverage for the browser, desktop and Android hosts. */
export const RUNNER_E2E_SUITES = defineSuites([
  {
    id: 'runner.chromium',
    environment: 'browser',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-browser:runner-smoke',
    targetProject: 'trinity-e2e-browser',
    prerequisites: ['chrome', 'chromedriver', 'docker', 'node-24'],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:runner:chromium',
    currentArtifactRoot: artifactRoot('trinity-e2e-browser'),
    targetArtifactRoot: artifactRoot('trinity-e2e-browser'),
    sourceEntrypoints: ['e2e/browser/runner-smoke.mts'],
  },
  {
    id: 'runner.electron',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-electron:runner-smoke',
    targetProject: 'trinity-e2e-electron',
    prerequisites: [
      'docker',
      'electron',
      'electron-chromedriver',
      'node-24',
      'xvfb',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['electron', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:runner:electron',
    currentArtifactRoot: artifactRoot('trinity-e2e-electron'),
    targetArtifactRoot: artifactRoot('trinity-e2e-electron'),
    sourceEntrypoints: ['e2e/electron/runner-smoke.mts'],
  },
  {
    id: 'runner.android',
    environment: 'android',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:runner-smoke',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:runner:android',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/runner-smoke.mts'],
  },
  {
    id: 'android.critical-journeys',
    environment: 'android',
    capabilities: ['accounts', 'conversations', 'trust', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:critical-journeys',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:critical',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/critical-journeys.mts'],
  },
  {
    id: 'android.native-shell',
    environment: 'android',
    capabilities: ['accounts', 'conversations', 'settings', 'host-shell'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:native-shell',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:native-shell',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/native-shell-journeys.mts'],
  },
  {
    id: 'android.accounts-workspace',
    environment: 'android',
    capabilities: ['accounts', 'conversations'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:accounts-workspace',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host-extended',
    canonicalScript: 'e2e:android:accounts',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/account-workspace-journeys.mts'],
  },
  {
    id: 'android.identity-presence',
    environment: 'android',
    capabilities: ['identity'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:identity-presence',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:identity',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/identity-presence-journeys.mts'],
  },
  {
    id: 'android.sidebar-filter',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:sidebar-filter',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:sidebar-filter',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/sidebar-filter-journeys.mts'],
  },
  {
    id: 'android.sidebar-touch',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:sidebar-touch',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:sidebar-touch',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/sidebar-touch-journeys.mts'],
  },
  {
    id: 'android.room-tags',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-tags',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-tags',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-tags-journeys.mts'],
  },
  {
    id: 'android.room-read-state',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-read-state',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-read-state',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-read-state-journeys.mts'],
  },
  {
    id: 'android.room-list',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-list',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-list',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-list-journeys.mts'],
  },
  {
    id: 'android.unread-badges',
    environment: 'android',
    capabilities: ['room-library', 'notifications'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:unread-badges',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:unread-badges',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/unread-badges-journeys.mts'],
  },
  {
    id: 'android.leave-room',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:leave-room',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:leave-room',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/leave-room-journeys.mts'],
  },
  {
    id: 'android.recent-activity',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:recent-activity',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:recent-activity',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/recent-activity-journeys.mts'],
  },
  {
    id: 'android.room-filter-spaceless',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-filter-spaceless',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-filter-spaceless',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-filter-spaceless-journeys.mts'],
  },
  {
    id: 'android.space-curation-create-join',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-curation-create-join',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-curation-create-join',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-curation-create-join-journeys.mts'],
  },
  {
    id: 'android.space-room-order',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-room-order',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-room-order',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-room-order-journeys.mts'],
  },
  {
    id: 'android.room-http-error-recovery',
    environment: 'android',
    capabilities: ['room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-http-error-recovery',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-http-error-recovery',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-http-error-recovery-journeys.mts'],
  },
  {
    id: 'android.room-settings-mobile',
    environment: 'android',
    capabilities: ['conversations', 'room-administration', 'settings'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-settings-mobile',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-settings-mobile',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-settings-mobile-journeys.mts'],
  },
  {
    id: 'android.space-settings-mobile',
    environment: 'android',
    capabilities: ['room-administration', 'room-library', 'settings'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-settings-mobile',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-settings-mobile',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-settings-mobile-journeys.mts'],
  },
  {
    id: 'android.space-settings-resilience',
    environment: 'android',
    capabilities: ['room-administration', 'room-library', 'settings'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-settings-resilience',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-settings-resilience',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-settings-resilience-journeys.mts'],
  },
  {
    id: 'android.space-settings-core',
    environment: 'android',
    capabilities: ['room-administration', 'room-library', 'settings'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-settings-core',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-settings-core',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-settings-core-journeys.mts'],
  },
  {
    id: 'android.space-leave',
    environment: 'android',
    capabilities: ['room-administration', 'room-library'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:space-leave',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:space-leave',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/space-leave-journeys.mts'],
  },
  {
    id: 'android.room-tombstone',
    environment: 'android',
    capabilities: ['room-administration', 'room-library'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-tombstone',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-tombstone',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-tombstone-journeys.mts'],
  },
  {
    id: 'android.member-details-promotion',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:member-details-promotion',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:member-details-promotion',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/member-details-promotion-journeys.mts'],
  },
  {
    id: 'android.member-role-classification',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:member-role-classification',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:member-role-classification',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/member-role-classification-journeys.mts'],
  },
  {
    id: 'android.member-role-live-updates',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:member-role-live-updates',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:member-role-live-updates',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/member-role-live-updates-journeys.mts'],
  },
  {
    id: 'android.message-moderation',
    environment: 'android',
    capabilities: ['room-administration', 'conversations'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-moderation',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-moderation',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/message-moderation-journeys.mts'],
  },
  {
    id: 'android.member-moderation',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:member-moderation',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:member-moderation',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/member-moderation-journeys.mts'],
  },
  {
    id: 'android.room-unban',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-unban',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-unban',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-unban-journeys.mts'],
  },
  {
    id: 'android.room-roster-live-authority',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-roster-live-authority',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-roster-live-authority',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-roster-live-authority-journeys.mts'],
  },
  {
    id: 'android.room-address-lifecycle',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-address-lifecycle',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-address-lifecycle',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-address-lifecycle-journeys.mts'],
  },
  {
    id: 'android.room-access-policy',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-access-policy',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-access-policy',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-access-policy-journeys.mts'],
  },
  {
    id: 'android.room-profile-settings',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-profile-settings',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-profile-settings',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-profile-settings-journeys.mts'],
  },
  {
    id: 'android.room-for-you',
    environment: 'android',
    capabilities: ['room-administration', 'notifications'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-for-you',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-for-you',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-for-you-journeys.mts'],
  },
  {
    id: 'android.room-widget-settings',
    environment: 'android',
    capabilities: ['room-administration'],
    contractTypes: ['host', 'journey', 'accessibility', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:room-widget-settings',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:room-widget-settings',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/room-widget-journeys.mts'],
  },
  {
    id: 'android.account-password-change',
    environment: 'android',
    capabilities: ['accounts', 'settings'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:account-password-change',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:account-password-change',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/account-password-change-journeys.mts'],
  },
  {
    id: 'android.clear-all-data',
    environment: 'android',
    capabilities: ['accounts', 'settings', 'host-shell'],
    contractTypes: ['host', 'journey', 'visual', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:clear-all-data',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:clear-all-data',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/clear-all-data-journeys.mts'],
  },
  {
    id: 'android.password-registration',
    environment: 'android',
    capabilities: ['accounts'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:password-registration',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:password-registration',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/password-registration-journeys.mts'],
  },
  {
    id: 'android.oidc-login',
    environment: 'android',
    capabilities: ['accounts', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:oidc-login',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:oidc-login',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/oidc-login-journeys.mts'],
  },
  {
    id: 'android.security-settings',
    environment: 'android',
    capabilities: ['accounts', 'settings', 'trust'],
    contractTypes: ['host', 'journey', 'security', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:security-settings',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:security-settings',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/security-settings-journeys.mts'],
  },
  {
    id: 'android.recovery-reset',
    environment: 'android',
    capabilities: ['accounts', 'settings', 'trust'],
    contractTypes: ['host', 'journey', 'security', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:recovery-reset',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:recovery-reset',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/recovery-reset-journeys.mts'],
  },
  {
    id: 'android.legacy-sso',
    environment: 'android',
    capabilities: ['accounts', 'host'],
    contractTypes: ['host', 'journey', 'security', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:legacy-sso',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'chrome',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:legacy-sso',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/legacy-sso-journeys.mts'],
  },
  {
    id: 'android.sso-recovery-reset',
    environment: 'android',
    capabilities: ['accounts', 'host', 'settings', 'trust'],
    contractTypes: ['host', 'journey', 'security', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:sso-recovery-reset',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'chrome',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:sso-recovery-reset',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/sso-recovery-reset-journeys.mts'],
  },
  {
    id: 'android.message-authenticity-shield',
    environment: 'android',
    capabilities: ['conversations', 'trust'],
    contractTypes: ['journey', 'security', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-authenticity-shield',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-authenticity-shield',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/message-authenticity-shield-journeys.mts'],
  },
  {
    id: 'android.cross-user-verification',
    environment: 'android',
    capabilities: ['conversations', 'trust'],
    contractTypes: ['journey', 'security', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:cross-user-verification',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:cross-user-verification',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/cross-user-verification-journeys.mts',
      'e2e/android/cross-user-verification-query-delay.mts',
    ],
  },
  {
    id: 'android.composer-drafts',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:composer-drafts',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:composer-drafts',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/composer-drafts-journeys.mts',
      'e2e/android/composer-drafts-preference.mts',
    ],
  },
  {
    id: 'android.composer-formatting',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:composer-formatting',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:composer-formatting',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/composer-formatting-journeys.mts',
      'e2e/android/composer-formatting-contract.mts',
    ],
  },
  {
    id: 'android.composer-mentions',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:composer-mentions',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:composer-mentions',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/composer-mentions-journeys.mts',
      'e2e/android/composer-mentions-contract.mts',
    ],
  },
  {
    id: 'android.composer-reactions',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:composer-reactions',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:composer-reactions',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/composer-reactions-journeys.mts',
      'e2e/android/composer-reactions-contract.mts',
    ],
  },
  {
    id: 'android.composer-typing',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey', 'accessibility'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:composer-typing',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:composer-typing',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/composer-typing-journeys.mts',
      'e2e/android/composer-typing-contract.mts',
    ],
  },
  {
    id: 'android.gif-picker',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:gif-picker',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:gif-picker',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/gif-picker-journeys.mts',
      'e2e/android/gif-picker-contract.mts',
      'e2e/android/gif-provider-fixture.mts',
      'e2e/android/gif-native-preference.mts',
    ],
  },
  {
    id: 'android.hide-system-messages',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:hide-system-messages',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:hide-system-messages',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/hide-system-messages-journeys.mts',
      'e2e/android/hide-system-messages-contract.mts',
      'e2e/android/timeline-membership-preference.mts',
    ],
  },
  {
    id: 'android.jump-to-date',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:jump-to-date',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:jump-to-date',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/jump-to-date-journeys.mts',
      'e2e/android/jump-to-date-contract.mts',
      'e2e/android/jump-to-date-network-observer.mts',
    ],
  },
  {
    id: 'android.jump-to-latest',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:jump-to-latest',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:jump-to-latest',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/jump-to-latest-journeys.mts',
      'e2e/android/jump-to-latest-contract.mts',
    ],
  },
  {
    id: 'android.link-preview',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:link-preview',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:link-preview',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/link-preview-journeys.mts',
      'e2e/android/link-preview-contract.mts',
      'e2e/android/link-preview-network-observer.mts',
    ],
  },
  {
    id: 'android.location-share',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:location-share',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:location-share',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/location-share-journeys.mts',
      'e2e/android/location-share-contract.mts',
      'e2e/android/native-location-adapter.mts',
    ],
  },
  {
    id: 'android.media-retention',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:media-retention',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:media-retention',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/media-retention-journeys.mts',
      'e2e/android/media-retention-contract.mts',
      'e2e/android/media-retention-fixture.mts',
    ],
  },
  {
    id: 'android.message-action-sheet',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-action-sheet',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-action-sheet',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-action-sheet-journeys.mts',
      'e2e/android/message-action-sheet-contract.mts',
      'e2e/android/message-action-sheet-observer.mts',
      'e2e/android/message-action-sheet-artifacts.mts',
    ],
  },
  {
    id: 'android.edit-history',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:edit-history',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:edit-history',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/edit-history-journeys.mts',
      'e2e/android/edit-history-contract.mts',
      'e2e/android/edit-history-fixture.mts',
      'e2e/android/edit-history-observer.mts',
      'e2e/android/edit-history-artifacts.mts',
    ],
  },
  {
    id: 'android.message-forward',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-forward',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-forward',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-forward-journeys.mts',
      'e2e/android/message-forward-contract.mts',
      'e2e/android/message-forward-artifacts.mts',
    ],
  },
  {
    id: 'android.message-grouping',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-grouping',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-grouping',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-grouping-journeys.mts',
      'e2e/android/message-grouping-contract.mts',
      'e2e/android/appearance-density-preference.mts',
      'e2e/android/message-grouping-artifacts.mts',
    ],
  },
  {
    id: 'android.message-linkify',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-linkify',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-linkify',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-linkify-journeys.mts',
      'e2e/android/message-linkify-contract.mts',
      'e2e/android/message-linkify-artifacts.mts',
    ],
  },
  {
    id: 'android.message-links',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-links',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-links',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-links-journeys.mts',
      'e2e/android/message-links-contract.mts',
      'e2e/android/message-links-fixtures.mts',
      'e2e/android/message-links-observer.mts',
      'e2e/android/message-links-artifacts.mts',
    ],
  },
  {
    id: 'android.message-markdown',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-markdown',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-markdown',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-markdown-journeys.mts',
      'e2e/android/message-markdown-contract.mts',
      'e2e/android/message-markdown-observer.mts',
      'e2e/android/message-markdown-artifacts.mts',
    ],
  },
  {
    id: 'android.message-poll',
    environment: 'android',
    capabilities: ['conversations'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:message-poll',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:message-poll',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: [
      'e2e/android/message-poll-journeys.mts',
      'e2e/android/message-poll-contract.mts',
      'e2e/android/message-poll-observer.mts',
      'e2e/android/message-poll-artifacts.mts',
    ],
  },
] as const);
