import { defineSuites } from '../types.mts';

const artifactRoot = (targetProject: string): string =>
  `dist/.playwright/${targetProject}/<run-id>`;

/** Node test runner coverage for the browser, desktop and Android hosts. */
export const RUNNER_E2E_SUITES = defineSuites([
  {
    id: 'runner.chromium',
    environment: 'browser',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-browser:runner-smoke',
    targetProject: 'trinity-e2e-browser',
    prerequisites: ['chrome', 'chromedriver', 'docker', 'node-24'],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['synapse'],
    timeoutClass: 'long',
    canonicalScript: 'e2e:runner:chromium',
    currentArtifactRoot: artifactRoot('trinity-e2e-browser'),
    targetArtifactRoot: artifactRoot('trinity-e2e-browser'),
    sourceEntrypoints: ['e2e/browser/runner-smoke.mts'],
  },
  {
    id: 'runner.electron',
    environment: 'electron',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-electron:runner-smoke',
    targetProject: 'trinity-e2e-electron',
    prerequisites: [
      'docker',
      'electron',
      'electron-chromedriver',
      'node-24',
      'xvfb',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['electron', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:runner:electron',
    currentArtifactRoot: artifactRoot('trinity-e2e-electron'),
    targetArtifactRoot: artifactRoot('trinity-e2e-electron'),
    sourceEntrypoints: ['e2e/electron/runner-smoke.mts'],
  },
  {
    id: 'runner.android',
    environment: 'android',
    capabilities: ['composition', 'host'],
    contractTypes: ['host', 'journey'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:runner-smoke',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:runner:android',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/runner-smoke.mts'],
  },
  {
    id: 'android.critical-journeys',
    environment: 'android',
    capabilities: ['accounts', 'conversations', 'trust', 'host'],
    contractTypes: ['host', 'journey', 'security'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:critical-journeys',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:critical',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/critical-journeys.mts'],
  },
  {
    id: 'android.native-shell',
    environment: 'android',
    capabilities: ['accounts', 'conversations', 'settings', 'host-shell'],
    contractTypes: ['host', 'journey', 'accessibility', 'visual'],
    runner: 'node-test',
    currentTarget: 'trinity-e2e-android:native-shell',
    targetProject: 'trinity-e2e-android',
    prerequisites: [
      'android-avd',
      'android-sdk',
      'docker',
      'java-21',
      'kvm',
      'maestro',
      'node-24',
    ],
    availabilityPolicy: 'required',
    ciTier: 'pull-request',
    cachePolicy: 'never',
    serializationKeys: ['android-avd', 'synapse'],
    timeoutClass: 'host',
    canonicalScript: 'e2e:android:native-shell',
    currentArtifactRoot: artifactRoot('trinity-e2e-android'),
    targetArtifactRoot: artifactRoot('trinity-e2e-android'),
    sourceEntrypoints: ['e2e/android/native-shell-journeys.mts'],
  },
] as const);
